pub const ATTESTATION_COMMITTEE_COUNT: u64 = 1;
pub const GOSSIP_DISPARITY_INTERVALS: u64 = 1;
pub const INTERVALS_PER_SLOT: u64 = 5;
pub const MAX_ATTESTATIONS_DATA: u64 = 16;
pub const MAX_HISTORICAL_BLOCK_HASHES: u64 = 262144;
pub const SLOT_DURATION: u64 = 4;
pub const VALIDATOR_REGISTRY_LIMIT: u64 = 4096;
