services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    restart: unless-stopped
    volumes:
      - ./tools/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./tools/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./tools/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./tools/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - 3000:3000

volumes:
  prometheus_data:

networks: {}
