[book]
authors = ["Ream Contributors"]
language = "en"
multilingual = false
src = "book"
title = "ream Book"

[build]
build-dir = "target/book"

[output.html]
no-section-label = true

[output.html.fold]
enable = true
level = 1
