binop_separator = "Front"
comment_width = 100
doc_comment_code_block_width = 100
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
normalize_comments = true
reorder_imports  = true
use_small_heuristics = "Max"
wrap_comments = true