# cargo-sort configuration
## https://github.com/DevinR528/cargo-sort

key_value_newlines = true
trailing_newline = true
# remove all the spacing inside the array
compact_arrays = false
# trailing comma when multi-line
multiline_trailing_comma = true
# The user specified ordering of tables in a document.
# All unspecified tables will come after these.
table_order = []
