pub const ATTESTATION_SUBNET_COUNT: u64 = 64;
pub const BLOB_SIDECAR_SUBNET_COUNT_ELECTRA: u64 = 9;
pub const SYNC_COMMITTEE_SUBNET_COUNT: u64 = 4;
pub const TARGET_AGGREGATORS_PER_COMMITTEE: u64 = 16;
