name: 'Install mdBook'
description: 'Installs the latest version of mdBook'

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
        url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
        curl -sSL $url | sudo tar -xz --directory=/usr/local/bin
        sudo chmod +x /usr/local/bin/mdbook
        mdbook --version
