[package]
name = "ream-chain-lean"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
alloy-primitives.workspace = true
anyhow.workspace = true
serde.workspace = true
ssz_types.workspace = true
tokio.workspace = true
tracing.workspace = true
tree_hash.workspace = true

# ream dependencies
ream-consensus-lean.workspace = true
ream-consensus-misc.workspace = true
ream-fork-choice.workspace = true
ream-metrics.workspace = true
ream-network-spec.workspace = true
ream-storage.workspace = true
ream-sync.workspace = true

[lints]
workspace = true
