[package]
name = "ream"
description = "A Rust implementation of the Ethereum Beam Chain specification."
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "ream"
path = "src/main.rs"

[dependencies]
# ream dependencies
ream-discv5.workspace = true
ream-executor.workspace = true 
ream-network-spec.workspace = true 
ream-p2p.workspace = true 
ream-rpc.workspace = true
ream-storage.workspace = true


# other dependencies
clap = { workspace = true, features = ["derive", "env"] }
discv5 = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tokio = { workspace = true }
