name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-devnet3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Test Devnet 3
        run: make test-devnet3
