name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust nightly
      run: rustup install nightly

    - name: Install rustfmt for nightly
      run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt

    - name: Run rustfmt
      run: cargo +nightly fmt -- --check

  cargo-clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Clippy
      run: |
        cargo clippy --all --all-targets --no-deps -- --deny warnings # clippy for ream, default features
        cargo clippy --package ream-bls --all-targets --features "supranational" --no-deps -- --deny warnings # clippy for ream-bls, supranational feature

  cargo-sort:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install this commit as there isn't a release yet which works for workspace's
    - name: Install cargo sort
      run: cargo install --git https://github.com/DevinR528/cargo-sort.git --rev 25a60ad860ce7cd0055abf4b69c18285cb07ab41 cargo-sort

    - name: Run cargo sort
      run: cargo sort --grouped --check --workspace

  build:
    runs-on: ubuntu-latest
    needs: [cargo-fmt, cargo-clippy]

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    needs: [cargo-fmt, cargo-clippy]

    steps:
    - uses: actions/checkout@v4

    - name: Test
      run: cargo test --release --workspace -- --nocapture

    - name: Test consensus spec tests
      run: cd testing/ef-tests && make test
