name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-udeps:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install cargo udeps
      run: cargo install cargo-udeps

    - name: Run cargo udeps
      run: cargo +nightly udeps --workspace --tests --all-targets --release --exclude ef-tests
