name: RISC-V

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-sp1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install toolchain
      run: |
        git clone https://github.com/succinctlabs/sp1
        cd sp1
        cd crates
        cd cli
        cargo install --locked --force --path .
        cd ~
        cargo prove install-toolchain
        rustup default succinct
        RUSTUP_TOOLCHAIN=succinct cargo --version


    - name: Build SP1
      run: cargo build --target=riscv32im-succinct-zkvm-elf -p ream-consensus-beacon -p ream-consensus-misc -p ream-bls

  build-risc0:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install toolchain
      run: |
        curl -L https://risczero.com/install | bash
        /home/runner/.risc0/bin/rzup install
        /home/runner/.risc0/bin/rzup install rust 1.88.0
        rustup default risc0
        
    - name: Build Risc0
      run: cargo build --target=riscv32im-risc0-zkvm-elf -p ream-consensus-beacon -p ream-consensus-misc -p ream-bls

